version: '2'
services:
  wpdb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: thisisthepassword
    volumes:
      - ./mysql:/var/lib/mysql
  wp:
    image: wordpress:php5.6
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wpdb
      WORDPRESS_DB_PASSWORD: thisisthepassword
    volumes:
      - ./uploads:/var/www/html/wp-content/uploads
      - ./plugins:/var/www/html/wp-content/plugins
      - ./theme:/var/www/html/wp-content/themes/theme
    links:
      - wpdb:mysql
